export const EVENTS = {
  // User Inputs
  USER_TEXT: 'USER_TEXT',
  
  // Voice
  VOICE_WAKE: 'VOICE_WAKE',
  VOICE_COMMAND: 'VOICE_COMMAND',
  
  // Gestures
  GESTURE_CONFIRM: 'GESTURE_CONFIRM',
  GESTURE_REJECT: 'GESTURE_REJECT',
  GESTURE_SEARCH: 'GESTURE_SEARCH',
  GESTURE_STOP: 'GESTURE_STOP',
  GESTURE_CLOSE: 'GESTURE_CLOSE',
  GESTURE_OPEN: 'GESTURE_OPEN',

  // Tasks
  TASK_CREATED: 'TASK_CREATED',
  TASK_UPDATED: 'TASK_UPDATED',
  TASK_COMPLETED: 'TASK_COMPLETED',
  TASK_FAILED: 'TASK_FAILED',

  // Models
  MODEL_SELECTED: 'MODEL_SELECTED',
  MODEL_FALLBACK: 'MODEL_FALLBACK',

  // Keys
  KEY_EXHAUSTED: 'KEY_EXHAUSTED',
  KEY_ROTATED: 'KEY_ROTATED',

  // Providers
  PROVIDER_STATUS_CHANGED: 'PROVIDER_STATUS_CHANGED',

  // Permissions
  PERMISSION_REQUESTED: 'PERMISSION_REQUESTED',
  PERMISSION_GRANTED: 'PERMISSION_GRANTED',
  PERMISSION_DENIED: 'PERMISSION_DENIED',

  // Confirmations
  CONFIRMATION_REQUESTED: 'CONFIRMATION_REQUESTED',
  CONFIRMATION_RESOLVED: 'CONFIRMATION_RESOLVED',

  // Screen / Context
  SCREEN_CHANGED: 'SCREEN_CHANGED',
  WINDOW_CHANGED: 'WINDOW_CHANGED',
  APPLICATION_OPENED: 'APPLICATION_OPENED',
  APPLICATION_CLOSED: 'APPLICATION_CLOSED',

  // Agent State
  AGENT_STATUS_CHANGED: 'AGENT_STATUS_CHANGED',
  AGENT_ERROR: 'AGENT_ERROR',
  AGENT_MESSAGE: 'AGENT_MESSAGE',
} as const;
